version: "3.7"
services:
 web_server:
   image: nginx:1.17.9-alpine
   ports:
     - "443:443"
     - "80:80"
   container_name: nginx
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./static/:/etc/nginx/static

 backend:
   image: rubensan112/django_app
   build:
    context: .
    dockerfile: Dockerfile
   container_name: backend
   ports:
     - "8081:8080"
   command: bash -c "python manage.py migrate && python manage.py collectstatic --clear --noinput && python manage.py runserver 0.0.0.0:8080"
   volumes:
     - ./static/:/app/static
   depends_on:
    - database 

 database:
   image: postgres:9.6.2-alpine
   ports:
     - "5432:5432"
   environment:
     POSTGRES_USER: django_user
     POSTGRES_PASSWORD: 1234
     POSTGRES_DB: django_database
   container_name: database
   volumes:
    - dbdata:/var/lib/postgresql/data

volumes:
 dbdata:
